In [1]:
import pandas as pd
import numpy as  np

## 导入数据 ## 查看数据 ##
f = open('E:/PyCharm/PycharmProjects/TTE/csvafterfilter2/10120830afterfilter2.csv')
df_test = pd.read_csv(f, dtype = {'taxi_id' : np.uint16, 'week' :np.int8, 'y_n' : np.uint8, 'lat1' : np.float32, 'long1' : np.float32, 'distance_interval' : np.float64, 'data_time_sec' : np.uint32, 'time_id' : np.uint})
df_test.head()


taxi_id  week  y_n  time_id       lat1       long1  distance_interval  \
0        1     5    1      420  30.696945  104.079491           0.100000   
1        1     5    1      420  30.696619  104.077637           0.180707   
2        1     5    1      423  30.696844  104.079178           0.149278   
3        1     5    1      425  30.703438  104.093239           1.531119   
4        1     5    1      425  30.705505  104.094460           0.257891   

   data_time_sec  
0          25220  
1          25250  
2          25382  
3          25505  
4          25537

In [2]:
del df_test['week']
del df_test['y_n']
del df_test['distance_interval']
del df_test['time_id']

In [3]:
df_test.head()

taxi_id       lat1       long1  data_time_sec
0        1  30.696945  104.079491          25220
1        1  30.696619  104.077637          25250
2        1  30.696844  104.079178          25382
3        1  30.703438  104.093239          25505
4        1  30.705505  104.094460          25537

In [13]:
df = df_test.values
romas = np.zeros(shape=(1000,10,4))
dfshape = 19513351 - 10
for i in range(1000):
    k=np.random.randint(0, high=dfshape, size=None, dtype='l')
    for j in range(k, k+10):
        romas[i][j-k] = df[j]
        romas[i][j-k][3] = df[j][2]
        romas[i][j-k][2] = df[j][1]
        romas[i][j-k][0] = i
        romas[i][j-k][1] = j-k
        # if df[j+1][0]!=df[j][0]:

print(romas)

[[[  0.           0.          30.65439796 104.01734161]
  [  0.           1.          30.65457726 104.01580811]
  [  0.           2.          30.65478516 104.01577759]
  ...
  [  0.          17.          30.65318871 103.9937439 ]
  [  0.          18.          30.65350342 103.9936676 ]
  [  0.          19.          30.65353394 103.9936676 ]]

 [[  1.           0.          30.63285828 104.03413391]
  [  1.           1.          30.63271523 104.03430939]
  [  1.           2.          30.63244247 104.03462219]
  ...
  [  1.          17.          30.62298012 104.05349731]
  [  1.          18.          30.62252617 104.05491638]
  [  1.          19.          30.62233925 104.05638123]]

 [[  2.           0.          30.63846397 104.12551117]
  [  2.           1.          30.63848114 104.1255722 ]
  [  2.           2.          30.63861084 104.1256485 ]
  ...
  [  2.          17.          30.63133049 104.14310455]
  [  2.          18.          30.63043594 104.14544678]
  [  2.          19.      

In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from collections import Counter
from numpy import *
import random
from sklearn.isotonic import IsotonicRegression
from sklearn import metrics
from hausdorff import hausdorff_distance
import pywt
import math
import copy

import warnings
warnings.filterwarnings("ignore")




In [3]:
f = open('E:/PyCharm/PycharmProjects/TTE/csvafterfilter2/20140830afterfilter2.csv')
df_test = pd.read_csv(f, dtype = {'taxi_id' : np.uint16, 'week' :np.int8, 'y_n' : np.uint8, 'lat1' : np.float32, 'long1' : np.float32, 'distance_interval' : np.float64, 'data_time_sec' : np.uint32, 'time_id' : np.uint})
del df_test['week']
del df_test['y_n']
del df_test['distance_interval']
del df_test['time_id']
df = df_test.values
romas = np.zeros(shape=(1000, 10, 4))
dfshape = 19513351 - 10
for i in range(1000):
    k = np.random.randint(0, high=dfshape, size=None, dtype='l')
    for j in range(k, k + 10):
        romas[i][j - k] = df[j]
        romas[i][j - k][3] = df[j][2]
        romas[i][j - k][2] = df[j][1]
        romas[i][j - k][0] = i
        romas[i][j - k][1] = j - k
print(romas)

[[[  0.           0.          30.66233444 104.05833435]
  [  0.           1.          30.66239929 104.05832672]
  [  0.           2.          30.66339874 104.05825043]
  ...
  [  0.           7.          30.66440582 104.05819702]
  [  0.           8.          30.66495514 104.05815125]
  [  0.           9.          30.66502953 104.05815125]]

 [[  1.           0.          30.64990616 104.0918045 ]
  [  1.           1.          30.64990044 104.09178162]
  [  1.           2.          30.64945984 104.09151459]
  ...
  [  1.           7.          30.648592   104.09117889]
  [  1.           8.          30.64859962 104.09117126]
  [  1.           9.          30.64860535 104.09116364]]

 [[  2.           0.          30.60554504 104.09879303]
  [  2.           1.          30.60555458 104.09879303]
  [  2.           2.          30.60555077 104.09879303]
  ...
  [  2.           7.          30.60556221 104.09880829]
  [  2.           8.          30.60555077 104.09881592]
  [  2.           9.      

In [4]:
a = romas
n = 10
labels = np.zeros(shape=(1000, 10))
labels.dtype = 'int64'
cluster_centers = np.zeros(shape=(n, 20))
for i in range(10):
    # print(i)
    clf = KMeans(n_clusters=n, random_state=9)
    y_pred = clf.fit_predict(a[:, i, 2:4])
    labels[:, i] = clf.labels_
    cluster_centers[:, 2 * i:(2 * i + 2)] = clf.cluster_centers_
print(labels)
np.savetxt('E:\PyCharm\PycharmProjects\differential-privacy-trajectory-data-publication\labels.csv', labels, delimiter = ',')
print(cluster_centers)
np.savetxt('E:\PyCharm\PycharmProjects\differential-privacy-trajectory-data-publication\cluster_centers.csv', cluster_centers, delimiter = ',')


[[6 0 3 ... 6 1 3]
 [6 0 3 ... 6 1 3]
 [5 9 5 ... 4 4 2]
 ...
 [6 3 3 ... 6 1 3]
 [6 0 3 ... 6 1 3]
 [9 6 2 ... 9 5 7]]
[[ 30.69511932 104.09929895  30.64406706 104.07690971  30.69406649
  104.09683793  30.57808284 103.97007815  30.68347598 103.9893378
   30.6835178  103.98894033  30.64785412 104.0259109   30.68423449
  104.10326105  30.86884356 103.82114029  30.68564816 104.10273902]
 [ 30.59853521 104.05984875  30.70069857 104.05075923  30.58263964
  104.05904587  30.64720802 104.02803467  30.64647807 104.07594251
   30.62529322 104.12133842  30.68430831 104.10356019  30.64675937
  104.02863428  30.64719081 104.07381854  30.64840503 104.02530359]
 [ 30.64571866 104.02708834  30.64833451 104.02803684  30.6648239
  103.99646471  30.69604225 104.3404541   30.57818806 103.96985595
   30.64750331 104.02702129  30.646427   104.07417842  30.70223861
  104.05048875  30.57946344 103.96950935  30.62508834 104.11947049]
 [ 30.57728428 103.97497304  30.68435394 104.10487447  30.6587681
  104.074

In [5]:
detailedpath = np.zeros(shape=(1000,20))
for i in range(1000):
    for j in range(10):
        x = labels[i,j]
        detailedpath[i,2*j] = cluster_centers[x,2*j]
        detailedpath[i,2*j+1] = cluster_centers[x,2*j+1]
print(detailedpath)
np.savetxt('E:\PyCharm\PycharmProjects\differential-privacy-trajectory-data-publication\detailedpath.csv', detailedpath, delimiter = ',')

[[ 30.65375198 104.07685478  30.64406706 ... 104.07381854  30.64649686
  104.07283435]
 [ 30.65375198 104.07685478  30.64406706 ... 104.07381854  30.64649686
  104.07283435]
 [ 30.62714605 104.12023627  30.62240419 ... 104.12013046  30.62508834
  104.11947049]
 ...
 [ 30.65375198 104.07685478  30.68435394 ... 104.07381854  30.64649686
  104.07283435]
 [ 30.65375198 104.07685478  30.64406706 ... 104.07381854  30.64649686
  104.07283435]
 [ 30.68353208 103.98461678  30.68580651 ... 103.98826015  30.68316893
  103.98697402]]


In [6]:
newpaths = []
for i in range(1000):
    newpath = ""
    for j in range(10):
        string = "L" + str(labels[i, j])
        newpath += string
    newpaths.append(newpath)
result = Counter(newpaths)
newpathsdict = dict(result)
print(newpathsdict)


{'L6L0L3L8L1L9L2L6L1L3': 138, 'L5L9L5L9L6L1L8L4L4L2': 83, 'L1L5L9L1L3L2L0L1L9L1': 2, 'L1L0L9L8L1L4L2L6L1L3': 18, 'L0L3L0L4L9L7L1L0L8L0': 102, 'L1L0L9L8L1L9L2L6L1L3': 6, 'L8L1L0L6L4L3L7L2L3L9': 8, 'L2L2L9L1L3L2L0L1L9L1': 78, 'L8L1L8L6L4L3L7L0L8L0': 1, 'L8L1L8L6L4L3L7L2L3L9': 59, 'L0L3L0L4L9L7L6L9L5L7': 1, 'L2L2L2L1L3L2L0L9L5L1': 4, 'L2L2L2L1L3L2L0L1L9L1': 40, 'L3L4L4L0L2L8L3L3L2L5': 46, 'L6L2L3L8L1L9L2L6L1L3': 2, 'L9L6L2L7L0L0L6L9L5L7': 57, 'L1L5L9L5L8L4L9L6L1L3': 1, 'L0L1L0L6L4L3L7L2L3L9': 23, 'L2L0L9L8L1L9L2L6L1L3': 2, 'L5L0L5L8L1L9L2L6L1L3': 6, 'L4L7L6L3L5L6L4L8L0L4': 2, 'L9L6L8L7L0L0L6L9L5L7': 19, 'L7L8L7L2L7L5L5L7L7L6': 4, 'L8L1L8L6L2L8L3L3L2L5': 1, 'L8L2L2L1L3L2L0L1L9L1': 3, 'L5L0L5L8L1L1L8L4L4L2': 5, 'L8L1L3L6L4L3L7L2L3L9': 14, 'L6L0L9L8L1L9L2L6L1L3': 19, 'L2L2L2L1L3L3L7L2L3L9': 1, 'L1L5L1L5L8L4L9L5L6L8': 55, 'L5L0L5L8L1L1L2L6L1L3': 2, 'L8L6L8L7L0L0L6L9L5L7': 4, 'L6L0L5L8L1L1L8L4L4L2': 1, 'L6L2L9L1L3L2L0L1L9L1': 1, 'L5L3L5L4L9L1L1L0L4L2': 6, 'L3L5L1L5L8L4L9L5L6L8': 1, 'L2L2L9L8L1

In [7]:
# 随机生成轨迹补足数量
while (len(newpathsdict) < 1000):
    key = ""
    for i in range(10):
        string = "L" + str(random.randint(0, n - 1))
        key += string
    newpathsdict.setdefault(key, 0)

# 补齐2的n次方haar变换和重构
values = list(newpathsdict.values())
a = int(math.log(len(values), 2))
for index in range(int(math.pow(2, a + 1)) - len(values)):
    values.append(0)


In [8]:
def list_sort_by_value(d):
    items = d.items()
    backitems = [[v[1], v[0]] for v in items]
    backitems.sort(reverse=True)
    return [backitems[i][1] for i in range(0, len(backitems))]

# 构建haar树
def haarWaveletTransform(data):
    coeffs = pywt.dwt(data, 'haar')
    # (cA, cD) : tuple   Approximation and detail coefficients.
    cA, cD = coeffs
    cA /= math.sqrt(2)
    cD /= math.sqrt(2)
    return cA,cD


def buildHaarTreeList(data):
    haarTreeList = []
    while(len(data)>=2):
        cA,cD = haarWaveletTransform(data)
        cD = cD.tolist()
        cD.reverse()
        # print(cA, cD)
        haarTreeList.extend(cD)
        data = cA
        if(len(data) == 1):
            cA = cA.tolist()
            cA.reverse()
            haarTreeList.extend(cA)
    haarTreeList.reverse()
    return haarTreeList

# 重建
def rebuildHaarTreeList(list):
    n = int(math.log(len(list), 2))
    # print(n)
    cA = list[0:1]
    for i in range(n):
        cD = list[int(math.pow(2,i)):int(math.pow(2,i+1))]
        data = math.sqrt(2) * pywt.idwt(cA, cD, 'haar')
        cA = data
    return data

# 添加噪声
def addNoise(n, eps):
    laplaceNoise = []
    h = math.log(n, 2)
    i=0
    while(i<n):
        if(i==0):
            layernumber = 0
        else:
            layernumber = int(math.log(i, 2))
        noise = np.random.laplace(0, (1+h)/ (eps * int(math.pow(2, h - layernumber))))
        laplaceNoise.append(noise)
        i = i+1
    return laplaceNoise



In [9]:
temp = buildHaarTreeList(values)
# print(len(temp))
noise = addNoise(len(temp), e)
c = [temp[i] + noise[i] for i in range(len(temp))]
noisecounts = rebuildHaarTreeList(c)
print(noisecounts)

[ 1.34733921e+02  8.22439272e+01  1.02328334e+01 ... -3.90891096e-01
 -1.29772935e+00 -1.29419504e-02]


In [10]:
i = 0
newpathsdict2 = copy.deepcopy(newpathsdict);
for key, value in newpathsdict.items():
    newpathsdict[key] = noisecounts[i]
    i = i + 1

valueslist = sorted(list(newpathsdict.values()), reverse=True)
#newpathslist是按噪声计数排序后的泛化轨迹
newpathslist = list_sort_by_value(newpathsdict)
print(newpathslist)

#按噪声计数排序对truecount排序
truecounts = []
for item in newpathslist:
    truecounts.append(newpathsdict2.get(item))
print(truecounts)



['L6L0L3L8L1L9L2L6L1L3', 'L0L3L0L4L9L7L1L0L8L0', 'L2L2L9L1L3L2L0L1L9L1', 'L5L9L5L9L6L1L8L4L4L2', 'L9L6L2L7L0L0L6L9L5L7', 'L8L1L8L6L4L3L7L2L3L9', 'L1L5L1L5L8L4L9L5L6L8', 'L3L4L4L0L2L8L3L3L2L5', 'L2L2L2L1L3L2L0L1L9L1', 'L0L1L0L6L4L3L7L2L3L9', 'L9L6L8L7L0L0L6L9L5L7', 'L6L0L9L8L1L9L2L6L1L3', 'L8L1L3L6L4L3L7L2L3L9', 'L1L0L9L8L1L4L2L6L1L3', 'L3L2L8L3L9L6L0L6L2L0', 'L0L1L0L6L4L3L1L0L8L0', 'L3L4L2L9L7L0L1L9L8L5', 'L7L8L7L2L7L5L5L7L7L6', 'L9L4L9L5L2L6L7L9L5L4', 'L5L0L1L3L4L9L0L2L4L9', 'L1L5L9L1L3L2L0L1L9L1', 'L6L2L3L1L1L9L2L6L1L3', 'L2L2L2L7L0L0L0L9L5L7', 'L9L6L2L7L0L0L6L9L5L1', 'L2L8L8L1L2L3L4L7L2L5', 'L8L1L8L6L4L3L7L0L8L0', 'L7L1L4L5L9L3L5L3L7L4', 'L2L1L8L3L6L6L6L2L9L8', 'L5L2L5L7L9L6L7L6L2L7', 'L6L8L8L9L5L0L8L2L1L7', 'L0L5L1L8L2L6L7L6L3L3', 'L7L3L5L9L4L1L0L0L5L3', 'L4L8L2L4L1L4L9L2L6L1', 'L8L1L0L6L4L3L7L2L3L9', 'L2L1L0L8L1L5L3L6L2L0', 'L2L2L9L1L3L2L0L1L1L3', 'L3L8L1L1L4L1L1L9L1L9', 'L2L2L5L8L9L8L3L9L8L6', 'L5L6L7L2L9L5L8L9L0L1', 'L2L3L0L9L8L2L0L0L2L0', 'L2L2L9L1L3L2L0L1L9L3', 'L7L8L7L2L7L7L5